configure: Add dependency query through pkg-config
See try_pkgconfig_dependency() and try_optional_pkgconfig_dependency()
functions documention.

Sources:
https://wiki.gentoo.org/wiki/Pkg-config
https://people.freedesktop.org/~dbn/pkg-config-guide.html

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -166,6 +166,59 @@ try_both_argument()
     fi
 }
 
+# Test if the specifced library could be used.
+# NOTE: This function will return failure if library is missing, use try_optional_pkgconfig_dependency()
+# when library is not required.
+# $1 - variable name for passing library linking flags
+# $2 - variable name for passing library compiler flags (include directiories etc.)
+# $3 - library name
+# $4 (Optional) - minimum required version based on pkg-config syntax for version checking.
+try_pkgconfig_dependency()
+{
+    info Checking whether the "$3" could be used...
+
+    if ! command -v pkg-config > /dev/null 2>&1; then
+        sub_info "Cannot find pkg-config for library query."
+        return 1
+    fi
+
+    if ! pkg-config --exists "$3"; then
+        sub_info "Not Found."
+        return 1;
+    fi
+
+    PKGCONFIG_RESULT_VERSION=$(pkg-config --modversion "$3")
+    if [ -n "$4" ] && [ "$PKGCONFIG_RESULT_VERSION" != "${4:-}" ]; then
+        sub_info "Incompatible version found: $(pkg-config --modversion "$3") vs $4".
+        return 1
+    fi
+
+    PKGCONFIG_RESULT_LIBS=$(pkg-config --libs "$3" "${4:-}" 2>/dev/null)
+    PKGCONFIG_RESULT_CFLAGS=$(pkg-config --cflags "$3" "${4:-}" 2>/dev/null)
+    sub_info "Found: $PKGCONFIG_RESULT_VERSION"
+    eval "$1=\"\${$1} \$PKGCONFIG_RESULT_LIBS\""
+    eval "$1=\${$1# }"
+    eval "$2=\"\${$2} \$PKGCONFIG_RESULT_CFLAGS\""
+    eval "$2=\${$2# }"
+    return 0
+}
+
+# Test if the specifced library could be used but disable a feature instead of failing out.
+# $1 - variable name for setting 1 or 0 based on library availablity
+# $2 - variable name for passing library linking flags
+# $3 - variable name for passing library compiler flags (include directiories etc.)
+# $4 - library name
+# $5 (Optional) - minimum required version based on pkg-config syntax for version checking.
+try_optional_pkgconfig_dependency()
+{
+    if try_pkgconfig_dependency "$2" "$3" "$4" "${5:-}"; then
+        eval "$1"=1
+    else
+        sub_info Skipping "$1" feature.
+        eval "$1"=0
+    fi
+}
+
 usage()
 {
     cat << _EOF
